### PR TITLE
Update outdated info in Creating an App Store Connect API Key guide

### PR DESCRIPTION
**Pull request by amandeepmittal**
This PR:
- Updates outdated screenshots and instructions for navigating through the App Store Connect API portal's dashboard to generate an API key.
- It also changes **App Store Connect Api** references to **App Store Connect API** because that's what is represented in the dashboard.

### CODE REVIEW

**Review by ide — APPROVED** [review]
Thanks for updating the guide and screenshots!

Did you compress the png images? I noticed they are 2-3x bigger in file size.

**Comment by amandeepmittal** [comment]
> Did you compress the png images? I noticed they are 2-3x bigger in file size.

I did. I think it is because of the image resolution. I'll re-check.

**Comment by amandeepmittal** [comment]
@ide, I've further optimized these images by reducing their width and height and then applying the compression technique.

**Comment by amandeepmittal** [comment]
I'm merging this but let me know if you think the optimizing these images isn't up to the mark. I compared the file sizes locally and after reducing the resolution and applying optimizing technique, it does seem to have an impact.

**Pull request merged**
